# Generated by Django 2.0.2 on 2018-06-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180602_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='FIELDNAME',
            new_name='image',
        ),
    ]
